// AUTO-GENERATED by tools/analyze-pf-forum.mjs
// Source project: D:\\GitHub\\modules-soft__pf-forum
// Files scanned: 101    Edges: 116
export const pfForumDemo = `# Generated by tools/analyze-pf-forum.mjs
# Project: D:\\GitHub\\modules-soft__pf-forum
# Colors:  .vue=green   .js=yellow   pinia=orange
# Each module exposes:  "in" (incoming imports), function rows, "deps" (outgoing imports).

groups:
  - { id: app, title: app · entry, color: cyan }
  - { id: entities, title: entities, color: magenta }
  - { id: features, title: features, color: magenta }
  - { id: widgets, title: widgets, color: cyan }
  - { id: pages, title: pages, color: green }
  - { id: shared, title: shared, color: gray }

nodes:
  - id: app_App_vue
    title: App.vue
    icon: app-window
    group: app
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 5, color: green, type: source }
  - id: app_main_js
    title: main.js
    icon: file-text
    group: app
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: app_router_js
    title: router.js
    icon: file-text
    group: app
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 11, color: yellow, type: source }
  - id: entities_auth_authStore_js
    title: authStore.js
    icon: database
    group: entities
    rows:
      - { id: in, icon: download, label: imported by, value: 5, color: orange, type: target }
      - { id: loginUser, icon: box, label: loginUser (Авторизация пользователя), color: orange, type: source }
      - { id: getUser, icon: box, label: getUser (Получение данных текущего пользователя), color: orange, type: source }
      - { id: logout, icon: box, label: logout (Выход из системы), color: orange, type: source }
      - { id: isAuthenticated, icon: box, label: isAuthenticated, color: orange, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: orange, type: source }
  - id: features_form_2_card_noms_components_Form2CardNoms_vue
    title: Form2CardNoms.vue
    icon: app-window
    group: features
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: updateFieldValues, icon: box, label: updateFieldValues, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: features_form_3_nom_components_card_EditableField_vue
    title: EditableField.vue
    icon: app-window
    group: features
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: startEdit, icon: box, label: startEdit, color: green, type: source }
      - { id: commit, icon: box, label: commit, color: green, type: source }
      - { id: cancel, icon: box, label: cancel, color: green, type: source }
      - { id: onTextInput, icon: box, label: onTextInput, color: green, type: source }
      - { id: onBoolChange, icon: box, label: onBoolChange, color: green, type: source }
      - { id: autoResize, icon: box, label: autoResize, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: features_form_3_nom_components_card_ReadonlyField_vue
    title: ReadonlyField.vue
    icon: app-window
    group: features
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: handleIconClick, icon: box, label: handleIconClick, color: green, type: source }
      - { id: handleFormClick, icon: box, label: handleFormClick, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: green, type: source }
  - id: features_form_3_nom_components_Form3Card_vue
    title: Form3Card.vue
    icon: app-window
    group: features
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: isWideField, icon: box, label: isWideField, color: green, type: source }
      - { id: handleFieldClick, icon: box, label: handleFieldClick, color: green, type: source }
      - { id: closeModal, icon: box, label: closeModal, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: green, type: source }
  - id: features_form_3_nom_utils_calculateHeight_js
    title: calculateHeight.js
    icon: file-text
    group: features
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: calculateHeight, icon: box, label: calculateHeight, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: pages_auth_PagesLogin_vue
    title: PagesLogin.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: validateForm, icon: box, label: validateForm, color: green, type: source }
      - { id: handleLogin, icon: box, label: handleLogin, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: pages_dev_RouteExplorer_vue
    title: RouteExplorer.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: isTestOrDevPath, icon: box, label: isTestOrDevPath, color: green, type: source }
      - { id: isTestOrDevGroup, icon: box, label: isTestOrDevGroup, color: green, type: source }
      - { id: getBasePrefix, icon: box, label: getBasePrefix, color: green, type: source }
      - { id: hasParams, icon: box, label: hasParams, color: green, type: source }
      - { id: extractParams, icon: box, label: extractParams, color: green, type: source }
      - { id: generatePath, icon: box, label: generatePath, color: green, type: source }
      - { id: canNavigate, icon: box, label: canNavigate, color: green, type: source }
      - { id: buildParamsState, icon: box, label: buildParamsState, color: green, type: source }
      - { id: fillDefaultsFor2Params, icon: box, label: fillDefaultsFor2Params, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: pages_dev_RouteParams_vue
    title: RouteParams.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: onInput, icon: box, label: onInput, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_form_1_PagesClients_vue
    title: PagesClients.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: resetData, icon: box, label: resetData, color: green, type: source }
      - { id: fetchClients, icon: box, label: fetchClients, color: green, type: source }
      - { id: handleRowClick, icon: box, label: handleRowClick, color: green, type: source }
      - { id: handlePageChange, icon: box, label: handlePageChange, color: green, type: source }
      - { id: handleSortChange, icon: box, label: "handleSortChange (Важно: как в первом компоненте (PaginatedData…)", color: green, type: source }
      - { id: handlePageSizeChange, icon: box, label: handlePageSizeChange, color: green, type: source }
      - { id: handleSearchChange, icon: box, label: handleSearchChange, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: pages_form_1_PagesTableWrapper_vue
    title: PagesTableWrapper.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: resetData, icon: box, label: resetData, color: green, type: source }
      - { id: fetchItems, icon: box, label: fetchItems, color: green, type: source }
      - { id: navigateToRow, icon: box, label: navigateToRow, color: green, type: source }
      - { id: updatePage, icon: box, label: updatePage, color: green, type: source }
      - { id: updateSort, icon: box, label: updateSort, color: green, type: source }
      - { id: updatePageSize, icon: box, label: updatePageSize, color: green, type: source }
      - { id: updateSearch, icon: box, label: updateSearch, color: green, type: source }
      - { id: updateDateRange, icon: box, label: updateDateRange, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: pages_form_2_PagesCardNoms_vue
    title: PagesCardNoms.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: filterFields, icon: box, label: filterFields, color: green, type: source }
      - { id: readAndUpdateFields, icon: box, label: readAndUpdateFields, color: green, type: source }
      - { id: resetData, icon: box, label: resetData, color: green, type: source }
      - { id: fetchOrderData, icon: box, label: fetchOrderData, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 4, color: green, type: source }
  - id: pages_form_2_PagesClientNoms_vue
    title: PagesClientNoms.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: resetData, icon: box, label: resetData, color: green, type: source }
      - { id: fetchNoms, icon: box, label: fetchNoms, color: green, type: source }
      - { id: updatePage, icon: box, label: updatePage, color: green, type: source }
      - { id: handleDateRangeChange, icon: box, label: handleDateRangeChange, color: green, type: source }
      - { id: handleSearchChange, icon: box, label: handleSearchChange, color: green, type: source }
      - { id: updateSorting, icon: box, label: updateSorting, color: green, type: source }
      - { id: updateItemsPerPage, icon: box, label: updateItemsPerPage, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: pages_form_3_PagesDetailNom_vue
    title: PagesDetailNom.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: resetData, icon: box, label: resetData, color: green, type: source }
      - { id: filterFields, icon: box, label: filterFields, color: green, type: source }
      - { id: readAndUpdateFields, icon: box, label: readAndUpdateFields, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: green, type: source }
  - id: pages_home_api_homeApi_js
    title: homeApi.js
    icon: file-text
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: tryFetch, icon: box, label: tryFetch, color: yellow, type: source }
      - { id: fetchNzpCard, icon: box, label: "fetchNzpCard (/nzp_totals_read.data.{sles,otk,pokr,upk,...}…)", color: yellow, type: source }
      - { id: fetchMonthlyCard, icon: box, label: "fetchMonthlyCard (2) Произв-во текущий месяц — /otgr_info, ищем…)", color: yellow, type: source }
      - { id: fetchOutsourceCard, icon: box, label: "fetchOutsourceCard (3) Аутсорс — /otgr_info?type=outsource)", color: yellow, type: source }
      - { id: fetchTotalStatsCard, icon: box, label: "fetchTotalStatsCard (либо /otgr_info?report=false&type=pf (на прод…)", color: yellow, type: source }
      - { id: fetchTotalWithVatCard, icon: box, label: "fetchTotalWithVatCard (5) Итого с НДС — /otgr_info?sale=true)", color: yellow, type: source }
      - { id: fetchSkladGpCard, icon: box, label: "fetchSkladGpCard (позднее: total_full / total_pf_sale, когда бэ…)", color: yellow, type: source }
      - { id: getDashboardKpi, icon: box, label: "getDashboardKpi (Совместимость: агрегированная функция (если г…)", color: yellow, type: source }
      - { id: getDashboardAnalysis, icon: box, label: getDashboardAnalysis (=============================================…), color: yellow, type: source }
      - { id: getDashboardFunnel, icon: box, label: getDashboardFunnel (=============================================…), color: yellow, type: source }
      - { id: getDashboardFlow, icon: box, label: getDashboardFlow, color: yellow, type: source }
      - { id: getDashboardKpiStats, icon: box, label: getDashboardKpiStats, color: yellow, type: source }
      - { id: params, icon: box, label: params, color: yellow, type: source }
      - { id: num, icon: box, label: num, color: yellow, type: source }
      - { id: fmtRu, icon: box, label: fmtRu, color: yellow, type: source }
      - { id: withTimeout, icon: box, label: withTimeout, color: yellow, type: source }
      - { id: get, icon: box, label: get, color: yellow, type: source }
      - { id: readTurnMillAll, icon: box, label: "readTurnMillAll (Читаем {turn, mill, all} по соглашению \`\${gro…)", color: yellow, type: source }
      - { id: readTurnMillAllPct, icon: box, label: "readTurnMillAllPct (Читаем процент (используется для потерь — \`\${…)", color: yellow, type: source }
      - { id: readScalar, icon: box, label: "readScalar (Скаляр: пробуем \`data.<group>\`, \`data.<group>…)", color: yellow, type: source }
      - { id: readShifts, icon: box, label: "readShifts (smeni_perc → объект вида {kpi_smena1t, kpi_sm…)", color: yellow, type: source }
      - { id: toIso, icon: box, label: toIso, color: yellow, type: source }
      - { id: calc, icon: box, label: calc, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: yellow, type: source }
  - id: pages_home_components_AnalysisChart_vue
    title: AnalysisChart.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_components_KpiCard_vue
    title: KpiCard.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_components_KpiStatsPanel_vue
    title: KpiStatsPanel.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: fmt, icon: box, label: fmt, color: green, type: source }
      - { id: fmtDec, icon: box, label: fmtDec, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_components_NzpCard_vue
    title: NzpCard.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: fmt, icon: box, label: fmt, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_components_ProductionFlow_vue
    title: ProductionFlow.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_components_ProductionFunnel_vue
    title: ProductionFunnel.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: pages_home_PagesHome_vue
    title: PagesHome.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: loadAll, icon: box, label: loadAll, color: green, type: source }
      - { id: fmt, icon: box, label: fmt, color: green, type: source }
      - { id: handle, icon: box, label: handle, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 7, color: green, type: source }
  - id: pages_home_stub_homeStub_js
    title: homeStub.js
    icon: file-text
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: pages_test_data_test_accounts_data_js
    title: "test-accounts.data.js"
    icon: file-text
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: pages_test_data_testing_access_data_js
    title: "testing-access.data.js"
    icon: file-text
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: pages_test_MarkdownRenderer_vue
    title: MarkdownRenderer.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 2, color: green, type: source }
  - id: pages_test_RoleAccounts_vue
    title: RoleAccounts.vue
    icon: app-window
    group: pages
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: copyToClipboard, icon: box, label: copyToClipboard, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_api_base_apiClient_js
    title: apiClient.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 6, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: yellow, type: source }
  - id: shared_api_base_authApi_js
    title: authApi.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: yellow, type: target }
      - { id: login, icon: box, label: login (Аутентификация пользователя), color: yellow, type: source }
      - { id: getUser, icon: box, label: getUser (Получение данных текущего пользователя), color: yellow, type: source }
      - { id: getMenu, icon: box, label: getMenu (Получение меню пользователя), color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_base_authClient_js
    title: authClient.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: yellow, type: source }
  - id: shared_api_base_responseHandlers_js
    title: responseHandlers.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 7, color: yellow, type: target }
      - { id: handleResponse, icon: box, label: handleResponse (Обработчик успешного ответа), color: yellow, type: source }
      - { id: handleError, icon: box, label: handleError (Обработчик ошибок), color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_api_base_tokenService_js
    title: tokenService.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 3, color: yellow, type: target }
      - { id: getToken, icon: box, label: getToken, color: yellow, type: source }
      - { id: setToken, icon: box, label: setToken, color: yellow, type: source }
      - { id: removeToken, icon: box, label: removeToken, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_api_form_1_clients_js
    title: clients.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: getClients, icon: box, label: getClients, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_form_1_list_js
    title: list.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: getItems, icon: box, label: getItems, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_form_2_nom_dir_js
    title: nom_dir.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: getClientNom, icon: box, label: getClientNom, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_form_2_nom_list_js
    title: nom_list.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: getNomById, icon: box, label: getNomById, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_form_3_nom_info_js
    title: nom_info.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: getNomDetailsById, icon: box, label: getNomDetailsById, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_api_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_api_update_js
    title: update.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: handleError, icon: box, label: handleError, color: yellow, type: source }
      - { id: sendBulkUpdate, icon: box, label: sendBulkUpdate, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_api_zagotovka_js
    title: zagotovka.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: getZagotovkaInfo, icon: box, label: getZagotovkaInfo (Получает информацию о заготовке), color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: yellow, type: source }
  - id: shared_forms_DateRangeFilters_vue
    title: DateRangeFilters.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: onStartDateChange, icon: box, label: onStartDateChange, color: green, type: source }
      - { id: onEndDateChange, icon: box, label: onEndDateChange, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_lib_formatters_js
    title: formatters.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 5, color: yellow, type: target }
      - { id: getTextAlignment, icon: box, label: getTextAlignment, color: yellow, type: source }
      - { id: formatValue, icon: box, label: formatValue, color: yellow, type: source }
      - { id: formatBoolean, icon: box, label: formatBoolean (helpers), color: yellow, type: source }
      - { id: formatNumber, icon: box, label: formatNumber, color: yellow, type: source }
      - { id: formatText, icon: box, label: formatText, color: yellow, type: source }
      - { id: isEmail, icon: box, label: isEmail, color: yellow, type: source }
      - { id: formatDate, icon: box, label: formatDate, color: yellow, type: source }
      - { id: formatTimestamp, icon: box, label: formatTimestamp, color: yellow, type: source }
      - { id: formatCurrency, icon: box, label: formatCurrency, color: yellow, type: source }
      - { id: isObject, icon: box, label: isObject, color: yellow, type: source }
      - { id: formatStrategy, icon: box, label: formatStrategy, color: yellow, type: source }
      - { id: getCallerStack, icon: box, label: getCallerStack, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_lib_localize_ru_js
    title: "localize-ru.js"
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_lib_useTheme_js
    title: useTheme.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: yellow, type: target }
      - { id: loadInitialTheme, icon: box, label: loadInitialTheme, color: yellow, type: source }
      - { id: applyTheme, icon: box, label: applyTheme, color: yellow, type: source }
      - { id: useTheme, icon: box, label: useTheme, color: yellow, type: source }
      - { id: toggle, icon: box, label: toggle, color: yellow, type: source }
      - { id: setTheme, icon: box, label: setTheme, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_logic_statuses_js
    title: statuses.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_tables_sborka_server_ServerSideSborka_vue
    title: ServerSideSborka.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: updateItemsPerPage, icon: box, label: updateItemsPerPage, color: green, type: source }
      - { id: updateStartDate, icon: box, label: updateStartDate, color: green, type: source }
      - { id: updateEndDate, icon: box, label: updateEndDate, color: green, type: source }
      - { id: onSearch, icon: box, label: onSearch, color: green, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 6, color: green, type: source }
  - id: shared_tables_sborka_PendingUpdatesOverlay_vue
    title: PendingUpdatesOverlay.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: confirmUpdates, icon: box, label: confirmUpdates, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_tables_sborka_SborMain_vue
    title: SborMain.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: createMatrix, icon: box, label: createMatrix, color: green, type: source }
      - { id: shouldMergeCells, icon: box, label: shouldMergeCells, color: green, type: source }
      - { id: mergeCellsInColumn, icon: box, label: mergeCellsInColumn, color: green, type: source }
      - { id: calculateRowSpanMatrix, icon: box, label: calculateRowSpanMatrix, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: green, type: source }
  - id: shared_tables_sborka_SborRow_vue
    title: SborRow.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: toggle, icon: box, label: toggle (Переключение строки), color: green, type: source }
      - { id: handleRowClick, icon: box, label: handleRowClick (Переход по строке), color: green, type: source }
      - { id: generateTitle, icon: box, label: generateTitle (Генерация заголовка), color: green, type: source }
      - { id: getFieldStyle, icon: box, label: getFieldStyle (Стили ячеек), color: green, type: source }
      - { id: getTreeNodeStyle, icon: box, label: "getTreeNodeStyle (Стили для \`tree-node\`)", color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 5, color: green, type: source }
  - id: shared_tables_table_server_DataTable_vue
    title: DataTable.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: handleSort, icon: box, label: handleSort, color: green, type: source }
      - { id: openEditModal, icon: box, label: openEditModal, color: green, type: source }
      - { id: closeModal, icon: box, label: closeModal, color: green, type: source }
      - { id: saveRowChanges, icon: box, label: saveRowChanges, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: green, type: source }
  - id: shared_tables_table_server_EditModal_vue
    title: EditModal.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: closeModal, icon: box, label: closeModal, color: green, type: source }
      - { id: saveChanges, icon: box, label: saveChanges, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_tables_table_server_PaginatedDataTable_vue
    title: PaginatedDataTable.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: fetchData, icon: box, label: fetchData (Имитация загрузки данных (заменить на реальны…), color: green, type: source }
      - { id: handleRowClick, icon: box, label: handleRowClick (Обработчики событий), color: green, type: source }
      - { id: sortBy, icon: box, label: sortBy, color: green, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: green, type: source }
      - { id: updateItemsPerPage, icon: box, label: updateItemsPerPage, color: green, type: source }
      - { id: updateDateRange, icon: box, label: updateDateRange, color: green, type: source }
      - { id: onSearch, icon: box, label: onSearch, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 7, color: green, type: source }
  - id: shared_tables_table_BaseTable_vue
    title: BaseTable.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: isEditing, icon: box, label: isEditing, color: green, type: source }
      - { id: startEdit, icon: box, label: startEdit, color: green, type: source }
      - { id: stopEdit, icon: box, label: stopEdit, color: green, type: source }
      - { id: openModal, icon: box, label: openModal, color: green, type: source }
      - { id: onCellClick, icon: box, label: onCellClick, color: green, type: source }
      - { id: cellTitle, icon: box, label: cellTitle, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: green, type: source }
  - id: shared_ui_DisplayStatus_vue
    title: DisplayStatus.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 3, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_DisplayStrategy_vue
    title: DisplayStrategy.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: getColor, icon: box, label: getColor, color: green, type: source }
      - { id: toggle, icon: box, label: toggle, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_ui_icons_js
    title: icons.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 3, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_LoadingProgressBar_vue
    title: LoadingProgressBar.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: animateProgress, icon: box, label: animateProgress (Функция для анимации), color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_ui_LoadingSpinner_vue
    title: LoadingSpinner.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_ui_LoadingTableSkeleton_vue
    title: LoadingTableSkeleton.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_ui_shadcn_badge_Badge_vue
    title: Badge.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_badge_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_card_Card_vue
    title: Card.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_CardContent_vue
    title: CardContent.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_CardDescription_vue
    title: CardDescription.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_CardFooter_vue
    title: CardFooter.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_CardHeader_vue
    title: CardHeader.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_CardTitle_vue
    title: CardTitle.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_card_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_lib_utils_js
    title: utils.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 16, color: yellow, type: target }
      - { id: cn, icon: box, label: "cn (cn — стандартный helper shadcn-vue для объеди…)", color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_progress_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_progress_Progress_vue
    title: Progress.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_separator_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_separator_Separator_vue
    title: Separator.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_skeleton_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_skeleton_Skeleton_vue
    title: Skeleton.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_index_js
    title: index.js
    icon: file-text
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: shared_ui_shadcn_table_Table_vue
    title: Table.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_TableBody_vue
    title: TableBody.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_TableCell_vue
    title: TableCell.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_TableHead_vue
    title: TableHead.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_TableHeader_vue
    title: TableHeader.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_ui_shadcn_table_TableRow_vue
    title: TableRow.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: shared_widgets_PageSizeSelect_vue
    title: PageSizeSelect.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_widgets_PaginationControl_vue
    title: PaginationControl.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: goToPage, icon: box, label: goToPage, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_widgets_SearchInput_vue
    title: SearchInput.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: green, type: target }
      - { id: onSearch, icon: box, label: onSearch, color: green, type: source }
      - { id: clearSearch, icon: box, label: clearSearch, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: shared_zagotovka_ModalZagotovka_vue
    title: ModalZagotovka.vue
    icon: app-window
    group: shared
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: fetchZagotovkaData, icon: box, label: fetchZagotovkaData, color: green, type: source }
      - { id: isObject, icon: box, label: isObject, color: green, type: source }
      - { id: closeModal, icon: box, label: closeModal, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: widgets_error_BaseToast_vue
    title: BaseToast.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: title, icon: box, label: title, color: green, type: source }
      - { id: toastClass, icon: box, label: toastClass, color: green, type: source }
      - { id: iconClass, icon: box, label: iconClass, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: green, type: source }
  - id: widgets_error_index_js
    title: index.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 0, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: widgets_error_store_js
    title: store.js
    icon: database
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 2, color: orange, type: target }
      - { id: show, icon: box, label: show, color: orange, type: source }
      - { id: showHttpError, icon: box, label: showHttpError, color: orange, type: source }
      - { id: hide, icon: box, label: hide, color: orange, type: source }
      - { id: push, icon: box, label: push, color: orange, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: orange, type: source }
  - id: widgets_layout_AppBreadcrumbs_vue
    title: AppBreadcrumbs.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: widgets_layout_AppHeader_vue
    title: AppHeader.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: fetchUser, icon: box, label: fetchUser, color: green, type: source }
      - { id: logout, icon: box, label: logout, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: green, type: source }
  - id: widgets_layout_AppMenu_vue
    title: AppMenu.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: toBiIcon, icon: box, label: toBiIcon, color: green, type: source }
      - { id: normalizeItem, icon: box, label: normalizeItem (Normalize API menu item to our internal shape), color: green, type: source }
      - { id: normalizeMenu, icon: box, label: normalizeMenu, color: green, type: source }
      - { id: isRouteAvailable, icon: box, label: isRouteAvailable, color: green, type: source }
      - { id: hasChildren, icon: box, label: hasChildren, color: green, type: source }
      - { id: isItemReachable, icon: box, label: isItemReachable, color: green, type: source }
      - { id: isDisabled, icon: box, label: isDisabled, color: green, type: source }
      - { id: isOpen, icon: box, label: isOpen, color: green, type: source }
      - { id: isActive, icon: box, label: isActive, color: green, type: source }
      - { id: toggleOpen, icon: box, label: toggleOpen, color: green, type: source }
      - { id: onItemClick, icon: box, label: onItemClick, color: green, type: source }
      - { id: rootTagFor, icon: box, label: rootTagFor, color: green, type: source }
      - { id: rootBindings, icon: box, label: rootBindings, color: green, type: source }
      - { id: toggleCollapsed, icon: box, label: toggleCollapsed, color: green, type: source }
      - { id: openActiveParent, icon: box, label: "openActiveParent (Auto-open the parent of the active route)", color: green, type: source }
      - { id: fetchUser, icon: box, label: fetchUser, color: green, type: source }
      - { id: fetchMenu, icon: box, label: fetchMenu, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: green, type: source }
  - id: widgets_layout_menuData_js
    title: menuData.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: widgets_modal_tools_api_tools_js
    title: tools.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: yellow, type: target }
      - { id: handleError, icon: box, label: handleError, color: yellow, type: source }
      - { id: fetchInstrumentData, icon: box, label: fetchInstrumentData, color: yellow, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: yellow, type: source }
  - id: widgets_modal_tools_components_AddedInstrumentsTable_vue
    title: AddedInstrumentsTable.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: generateUniqueId, icon: box, label: generateUniqueId, color: green, type: source }
      - { id: toggleCollapse, icon: box, label: toggleCollapse, color: green, type: source }
      - { id: isExpanded, icon: box, label: isExpanded, color: green, type: source }
      - { id: initialComments, icon: box, label: initialComments, color: green, type: source }
      - { id: additionalComments, icon: box, label: additionalComments, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: widgets_modal_tools_components_PagesModalTools_vue
    title: PagesModalTools.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: loadInstrumentData, icon: box, label: loadInstrumentData, color: green, type: source }
      - { id: generateUniqueId, icon: box, label: generateUniqueId, color: green, type: source }
      - { id: addInstrument, icon: box, label: addInstrument, color: green, type: source }
      - { id: removeInstrument, icon: box, label: removeInstrument, color: green, type: source }
      - { id: closeModal, icon: box, label: closeModal, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: green, type: source }
  - id: widgets_modal_tools_components_ProposedInstrumentsTable_vue
    title: ProposedInstrumentsTable.vue
    icon: app-window
    group: widgets
    rows:
      - { id: in, icon: download, label: imported by, value: 1, color: green, type: target }
      - { id: generateUniqueId, icon: box, label: generateUniqueId, color: green, type: source }
      - { id: toggleCollapse, icon: box, label: toggleCollapse, color: green, type: source }
      - { id: isExpanded, icon: box, label: isExpanded, color: green, type: source }
      - { id: initialComments, icon: box, label: initialComments, color: green, type: source }
      - { id: additionalComments, icon: box, label: additionalComments, color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }

edges:
  - { from: app_App_vue.deps, to: widgets_layout_AppHeader_vue.in, color: green }
  - { from: app_App_vue.deps, to: widgets_layout_AppMenu_vue.in, color: green }
  - { from: app_App_vue.deps, to: widgets_error_BaseToast_vue.in, color: green }
  - { from: app_App_vue.deps, to: entities_auth_authStore_js.in, color: green }
  - { from: app_App_vue.deps, to: shared_lib_useTheme_js.in, color: green }
  - { from: app_main_js.deps, to: app_router_js.in, color: yellow }
  - { from: app_main_js.deps, to: app_App_vue.in, color: yellow }
  - { from: app_router_js.deps, to: entities_auth_authStore_js.in, color: yellow }
  - { from: app_router_js.deps, to: pages_auth_PagesLogin_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_form_1_PagesTableWrapper_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_form_2_PagesCardNoms_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_form_3_PagesDetailNom_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_form_1_PagesClients_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_form_2_PagesClientNoms_vue.in, color: yellow }
  - { from: app_router_js.deps, to: widgets_modal_tools_components_PagesModalTools_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_test_MarkdownRenderer_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_home_PagesHome_vue.in, color: yellow }
  - { from: app_router_js.deps, to: pages_dev_RouteExplorer_vue.in, color: yellow }
  - { from: entities_auth_authStore_js.deps, to: shared_api_base_authApi_js.in, color: orange }
  - { from: entities_auth_authStore_js.deps, to: shared_api_base_tokenService_js.in, color: orange }
  - { from: features_form_2_card_noms_components_Form2CardNoms_vue.deps, to: shared_lib_formatters_js.in, color: green }
  - { from: features_form_3_nom_components_card_ReadonlyField_vue.deps, to: shared_ui_icons_js.in, color: green }
  - { from: features_form_3_nom_components_card_ReadonlyField_vue.deps, to: shared_lib_formatters_js.in, color: green }
  - { from: features_form_3_nom_components_Form3Card_vue.deps, to: features_form_3_nom_components_card_EditableField_vue.in, color: green }
  - { from: features_form_3_nom_components_Form3Card_vue.deps, to: features_form_3_nom_components_card_ReadonlyField_vue.in, color: green }
  - { from: features_form_3_nom_components_Form3Card_vue.deps, to: shared_zagotovka_ModalZagotovka_vue.in, color: green }
  - { from: pages_auth_PagesLogin_vue.deps, to: entities_auth_authStore_js.in, color: green }
  - { from: pages_dev_RouteExplorer_vue.deps, to: pages_dev_RouteParams_vue.in, color: green }
  - { from: pages_form_1_PagesClients_vue.deps, to: shared_tables_table_server_PaginatedDataTable_vue.in, color: green }
  - { from: pages_form_1_PagesTableWrapper_vue.deps, to: shared_tables_table_server_PaginatedDataTable_vue.in, color: green }
  - { from: pages_form_2_PagesCardNoms_vue.deps, to: features_form_2_card_noms_components_Form2CardNoms_vue.in, color: green }
  - { from: pages_form_2_PagesCardNoms_vue.deps, to: shared_tables_sborka_SborMain_vue.in, color: green }
  - { from: pages_form_2_PagesCardNoms_vue.deps, to: shared_ui_LoadingTableSkeleton_vue.in, color: green }
  - { from: pages_form_2_PagesCardNoms_vue.deps, to: shared_tables_table_BaseTable_vue.in, color: green }
  - { from: pages_form_2_PagesClientNoms_vue.deps, to: shared_tables_sborka_server_ServerSideSborka_vue.in, color: green }
  - { from: pages_form_3_PagesDetailNom_vue.deps, to: features_form_3_nom_components_Form3Card_vue.in, color: green }
  - { from: pages_form_3_PagesDetailNom_vue.deps, to: shared_tables_table_BaseTable_vue.in, color: green }
  - { from: pages_home_api_homeApi_js.deps, to: pages_home_stub_homeStub_js.in, color: yellow }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_api_homeApi_js.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_NzpCard_vue.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_KpiCard_vue.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_AnalysisChart_vue.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_ProductionFunnel_vue.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_ProductionFlow_vue.in, color: green }
  - { from: pages_home_PagesHome_vue.deps, to: pages_home_components_KpiStatsPanel_vue.in, color: green }
  - { from: pages_test_MarkdownRenderer_vue.deps, to: pages_test_data_testing_access_data_js.in, color: green }
  - { from: pages_test_MarkdownRenderer_vue.deps, to: pages_test_RoleAccounts_vue.in, color: green }
  - { from: shared_api_base_apiClient_js.deps, to: shared_api_base_tokenService_js.in, color: yellow }
  - { from: shared_api_base_authApi_js.deps, to: shared_api_base_authClient_js.in, color: yellow }
  - { from: shared_api_base_authApi_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_base_authClient_js.deps, to: shared_api_base_tokenService_js.in, color: yellow }
  - { from: shared_api_form_1_clients_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_form_1_clients_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_form_1_list_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_form_1_list_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_form_2_nom_dir_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_form_2_nom_dir_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_form_2_nom_list_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_form_2_nom_list_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_form_3_nom_info_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_form_3_nom_info_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_api_zagotovka_js.deps, to: shared_api_base_apiClient_js.in, color: yellow }
  - { from: shared_api_zagotovka_js.deps, to: shared_api_base_responseHandlers_js.in, color: yellow }
  - { from: shared_tables_sborka_SborMain_vue.deps, to: shared_tables_sborka_SborRow_vue.in, color: green }
  - { from: shared_tables_sborka_SborMain_vue.deps, to: shared_ui_icons_js.in, color: green }
  - { from: shared_tables_sborka_SborRow_vue.deps, to: shared_ui_icons_js.in, color: green }
  - { from: shared_tables_sborka_SborRow_vue.deps, to: shared_lib_formatters_js.in, color: green }
  - { from: shared_tables_sborka_SborRow_vue.deps, to: shared_ui_DisplayStatus_vue.in, color: green }
  - { from: shared_tables_sborka_SborRow_vue.deps, to: shared_ui_DisplayStrategy_vue.in, color: green }
  - { from: shared_tables_sborka_SborRow_vue.deps, to: widgets_error_store_js.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_widgets_SearchInput_vue.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_widgets_PaginationControl_vue.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_widgets_PageSizeSelect_vue.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_forms_DateRangeFilters_vue.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_tables_sborka_SborMain_vue.in, color: green }
  - { from: shared_tables_sborka_server_ServerSideSborka_vue.deps, to: shared_ui_LoadingTableSkeleton_vue.in, color: green }
  - { from: shared_tables_table_BaseTable_vue.deps, to: shared_ui_DisplayStatus_vue.in, color: green }
  - { from: shared_tables_table_BaseTable_vue.deps, to: shared_lib_formatters_js.in, color: green }
  - { from: shared_tables_table_server_DataTable_vue.deps, to: shared_ui_DisplayStatus_vue.in, color: green }
  - { from: shared_tables_table_server_DataTable_vue.deps, to: shared_tables_table_server_EditModal_vue.in, color: green }
  - { from: shared_tables_table_server_DataTable_vue.deps, to: shared_ui_LoadingSpinner_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_widgets_SearchInput_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_widgets_PaginationControl_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_widgets_PageSizeSelect_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_tables_table_server_DataTable_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_forms_DateRangeFilters_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_ui_LoadingProgressBar_vue.in, color: green }
  - { from: shared_tables_table_server_PaginatedDataTable_vue.deps, to: shared_lib_formatters_js.in, color: green }
  - { from: shared_ui_DisplayStatus_vue.deps, to: shared_logic_statuses_js.in, color: green }
  - { from: shared_ui_shadcn_badge_Badge_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_Card_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_CardContent_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_CardDescription_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_CardFooter_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_CardHeader_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_card_CardTitle_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_progress_Progress_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_separator_Separator_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_skeleton_Skeleton_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_Table_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_TableBody_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_TableCell_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_TableHead_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_TableHeader_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_ui_shadcn_table_TableRow_vue.deps, to: shared_ui_shadcn_lib_utils_js.in, color: green }
  - { from: shared_zagotovka_ModalZagotovka_vue.deps, to: shared_api_zagotovka_js.in, color: green }
  - { from: widgets_error_BaseToast_vue.deps, to: widgets_error_store_js.in, color: green }
  - { from: widgets_layout_AppHeader_vue.deps, to: entities_auth_authStore_js.in, color: green }
  - { from: widgets_layout_AppHeader_vue.deps, to: shared_lib_useTheme_js.in, color: green }
  - { from: widgets_layout_AppHeader_vue.deps, to: widgets_layout_AppBreadcrumbs_vue.in, color: green }
  - { from: widgets_layout_AppMenu_vue.deps, to: entities_auth_authStore_js.in, color: green }
  - { from: widgets_layout_AppMenu_vue.deps, to: shared_api_base_authApi_js.in, color: green }
  - { from: widgets_layout_AppMenu_vue.deps, to: widgets_layout_menuData_js.in, color: green }
  - { from: widgets_modal_tools_components_PagesModalTools_vue.deps, to: widgets_modal_tools_components_AddedInstrumentsTable_vue.in, color: green }
  - { from: widgets_modal_tools_components_PagesModalTools_vue.deps, to: widgets_modal_tools_components_ProposedInstrumentsTable_vue.in, color: green }
  - { from: widgets_modal_tools_components_PagesModalTools_vue.deps, to: widgets_modal_tools_api_tools_js.in, color: green }`
