// AUTO-GENERATED by tools/analyze-soft-pfforum.mjs
// Source project: D:\\GitHub\\soft.pfforum
// Files scanned: 69   Libraries: 4   Edges: 182

export const softPfforumDemo = `# Generated by tools/analyze-soft-pfforum.mjs
# Project: D:\\GitHub\\soft.pfforum (window-globals style, no ES modules)
# Sources scanned: dist/js/vue/**/*.js
# Libraries shown but not scanned: plugins/vue/{vue,pinia,axios,moment}.js
# Accent color: magenta

groups:
  - { id: template, title: template · entry apps, color: magenta }
  - { id: widgets, title: widgets, color: magenta }
  - { id: shared_api, title: shared · API, color: magenta }
  - { id: shared_lib, title: shared · lib, color: magenta }
  - { id: shared_stores, title: shared · stores, color: magenta }
  - { id: misc, title: misc, color: magenta }
  - { id: library, title: plugins/vue · libraries, color: yellow }

nodes:
  - id: dist_js_vue_config_js
    title: config.js
    icon: file-text
    group: misc
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_api_additional_production_js
    title: production.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_apiClient_js
    title: apiClient.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 13, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 3, color: magenta, type: source }
  - id: dist_js_vue_shared_api_client_index_js
    title: index.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 4, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_cnc_list_js
    title: list.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: normalize, icon: box, label: "_normalize (Docs: http://api.pfforum/api/docs#/)", color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_shared_api_index_js
    title: index.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_api_nom_actions_js
    title: actions.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 3, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_nom_list_js
    title: list.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 3, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_nom_zagotovka_js
    title: zagotovka.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_operations_index_js
    title: index.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_outsourcers_list_js
    title: list.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_spec_actions_js
    title: actions.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_spec_status_js
    title: status.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_specs_extra_ops_list_js
    title: list.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_api_tokenService_js
    title: tokenService.js
    icon: file-text
    group: shared_api
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_ApiToast_js
    title: ApiToast.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: getContainer, icon: box, label: getContainer, color: magenta, type: source }
      - { id: show, icon: box, label: show, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_datepicker_js
    title: datepicker.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 3, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_devFields_js
    title: devFields.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_fieldEndpoint_js
    title: fieldEndpoint.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: getByPath, icon: box, label: _getByPath (Универсальный), color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_fields_js
    title: fields.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: hasAccess, icon: box, label: _hasAccess, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_formatters_js
    title: formatters.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 8, color: magenta, type: target }
      - { id: formatNumber, icon: box, label: formatNumber, color: magenta, type: source }
      - { id: formatText, icon: box, label: formatText, color: magenta, type: source }
      - { id: formatDate, icon: box, label: formatDate, color: magenta, type: source }
      - { id: formatTimestamp, icon: box, label: formatTimestamp, color: magenta, type: source }
      - { id: formatCurrency, icon: box, label: formatCurrency, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_headerSummary_js
    title: headerSummary.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_notificationStore_js
    title: notificationStore.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 6, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_rowSpan_js
    title: rowSpan.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_statuses_js
    title: statuses.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_lib_tooltip_js
    title: tooltip.js
    icon: file-text
    group: shared_lib
    rows:
      - { id: in, icon: download, label: used by, value: 3, color: magenta, type: target }
      - { id: getTip, icon: box, label: getTip (shared/lib/tooltip.js — глобальный каст), color: magenta, type: source }
      - { id: show, icon: box, label: show, color: magenta, type: source }
      - { id: hide, icon: box, label: hide, color: magenta, type: source }
      - { id: showIfTruncated, icon: box, label: showIfTruncated, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_routes_js
    title: routes.js
    icon: file-text
    group: shared_routes_js
    rows:
      - { id: in, icon: download, label: used by, value: 4, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 0, color: magenta, type: source }
  - id: dist_js_vue_shared_stores_columns_js
    title: columns.js
    icon: file-text
    group: shared_stores
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_template_form_1_app_js
    title: "form-1-app.js"
    icon: file-text
    group: template
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: onEditClick, icon: box, label: onEditClick, color: magenta, type: source }
      - { id: onEditUpdated, icon: box, label: onEditUpdated, color: magenta, type: source }
      - { id: listExtraParams, icon: box, label: listExtraParams (extraParams для ListWidget + проброс в URL пр…), color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 6, color: magenta, type: source }
  - id: dist_js_vue_template_form_2_app_js
    title: "form-2-app.js"
    icon: file-text
    group: template
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: magenta, type: target }
      - { id: onSummary, icon: box, label: onSummary, color: magenta, type: source }
      - { id: commitInline, icon: box, label: commitInline, color: magenta, type: source }
      - { id: isCommentItem, icon: box, label: isCommentItem (они длинные и ломают выравнивание остальных п…), color: magenta, type: source }
      - { id: commentItems, icon: box, label: commentItems, color: magenta, type: source }
      - { id: pinnedItems, icon: box, label: pinnedItems, color: magenta, type: source }
      - { id: nonPinnedItems, icon: box, label: nonPinnedItems, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 7, color: magenta, type: source }
  - id: dist_js_vue_template_form_2_clientnoms_app_js
    title: "form-2-clientnoms-app.js"
    icon: file-text
    group: template
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: magenta, type: target }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: onFiltersApply, icon: box, label: onFiltersApply, color: magenta, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: magenta, type: source }
      - { id: totalPages, icon: box, label: totalPages, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 9, color: magenta, type: source }
  - id: dist_js_vue_template_form_3_app_js
    title: "form-3-app.js"
    icon: file-text
    group: template
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 5, color: magenta, type: source }
  - id: dist_js_vue_template_form_specs_dop_app_js
    title: "form-specs-dop-app.js"
    icon: file-text
    group: template
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 4, color: magenta, type: source }
  - id: dist_js_vue_widgets_base_table_BaseTableCell_js
    title: BaseTableCell.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: highlightHtml, icon: box, label: highlightHtml, color: magenta, type: source }
      - { id: StratCellComp, icon: box, label: StratCellComp, color: magenta, type: source }
      - { id: DisplayStatusComp, icon: box, label: DisplayStatusComp, color: magenta, type: source }
      - { id: cellValue, icon: box, label: cellValue, color: magenta, type: source }
      - { id: isEmpty, icon: box, label: isEmpty, color: magenta, type: source }
      - { id: isNameField, icon: box, label: isNameField, color: magenta, type: source }
      - { id: canOpenNewTab, icon: box, label: canOpenNewTab, color: magenta, type: source }
      - { id: fieldKey, icon: box, label: fieldKey, color: magenta, type: source }
      - { id: canCopy, icon: box, label: canCopy, color: magenta, type: source }
      - { id: normalize, icon: box, label: normalize, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 4, color: magenta, type: source }
  - id: dist_js_vue_widgets_base_table_BaseTableToolbar_js
    title: BaseTableToolbar.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: ColPanelComp, icon: box, label: ColPanelComp, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_base_table_StratCell_js
    title: StratCell.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: getColor, icon: box, label: getColor, color: magenta, type: source }
      - { id: entries, icon: box, label: entries, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_BaseTable_js
    title: BaseTable.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 4, color: magenta, type: target }
      - { id: rowKey, icon: box, label: _rowKey, color: magenta, type: source }
      - { id: buildHref, icon: box, label: buildHref, color: magenta, type: source }
      - { id: getRowHref, icon: box, label: getRowHref, color: magenta, type: source }
      - { id: handleRowClick, icon: box, label: handleRowClick, color: magenta, type: source }
      - { id: openNewTabRow, icon: box, label: openNewTabRow, color: magenta, type: source }
      - { id: fieldKey, icon: box, label: fieldKey, color: magenta, type: source }
      - { id: getCellStyle, icon: box, label: getCellStyle, color: magenta, type: source }
      - { id: isCommentField, icon: box, label: isCommentField, color: magenta, type: source }
      - { id: getRowStyle, icon: box, label: getRowStyle, color: magenta, type: source }
      - { id: isShippedRow, icon: box, label: isShippedRow, color: magenta, type: source }
      - { id: getRowClass, icon: box, label: getRowClass, color: magenta, type: source }
      - { id: getCellClasses, icon: box, label: getCellClasses, color: magenta, type: source }
      - { id: isCellEditable, icon: box, label: isCellEditable, color: magenta, type: source }
      - { id: onCellClick, icon: box, label: onCellClick, color: magenta, type: source }
      - { id: onRowClick, icon: box, label: onRowClick, color: magenta, type: source }
      - { id: onCellEnter, icon: box, label: onCellEnter, color: magenta, type: source }
      - { id: onCellLeave, icon: box, label: onCellLeave, color: magenta, type: source }
      - { id: toggleStratRow, icon: box, label: toggleStratRow, color: magenta, type: source }
      - { id: toggleStratExpanded, icon: box, label: toggleStratExpanded, color: magenta, type: source }
      - { id: toggleDevShowAllFields, icon: box, label: toggleDevShowAllFields, color: magenta, type: source }
      - { id: toggleTree, icon: box, label: toggleTree, color: magenta, type: source }
      - { id: copyCell, icon: box, label: copyCell, color: magenta, type: source }
      - { id: BaseTableToolbarComp, icon: box, label: BaseTableToolbarComp, color: magenta, type: source }
      - { id: BaseTableCellComp, icon: box, label: BaseTableCellComp, color: magenta, type: source }
      - { id: DevFieldsPanelComp, icon: box, label: DevFieldsPanelComp, color: magenta, type: source }
      - { id: devShowAllFields, icon: box, label: devShowAllFields, color: magenta, type: source }
      - { id: searchQuery, icon: box, label: searchQuery, color: magenta, type: source }
      - { id: devTableItems, icon: box, label: devTableItems, color: magenta, type: source }
      - { id: hiddenCols, icon: box, label: hiddenCols, color: magenta, type: source }
      - { id: displayFields, icon: box, label: "displayFields (Поля для отображения: видимые + опц. колонка…)", color: magenta, type: source }
      - { id: flattenedRows, icon: box, label: "flattenedRows (Каждый элемент: { row, depth, treeKey, hasChi…)", color: magenta, type: source }
      - { id: rowSpanMatrix, icon: box, label: "rowSpanMatrix (Матрица rowspan: считается только для топ-уро…)", color: magenta, type: source }
      - { id: hasStratField, icon: box, label: hasStratField, color: magenta, type: source }
      - { id: nomCodeColorMap, icon: box, label: nomCodeColorMap, color: magenta, type: source }
      - { id: walk, icon: box, label: walk (Поля для отобр), color: magenta, type: source }
      - { id: done, icon: box, label: done, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 12, color: magenta, type: source }
  - id: dist_js_vue_widgets_BreadcrumbNav_js
    title: BreadcrumbNav.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: isClickable, icon: box, label: isClickable (страница — не должен иметь href в передаваемы…), color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_ColPanel_js
    title: ColPanel.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: onDocClick, icon: box, label: _onDocClick, color: magenta, type: source }
      - { id: toggleCol, icon: box, label: toggleCol, color: magenta, type: source }
      - { id: resetCols, icon: box, label: resetCols, color: magenta, type: source }
      - { id: store, icon: box, label: store, color: magenta, type: source }
      - { id: hiddenCols, icon: box, label: hiddenCols, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_dev_DevFieldsPanel_js
    title: DevFieldsPanel.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_DisplayStatus_js
    title: DisplayStatus.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: formattedStatuses, icon: box, label: formattedStatuses, color: magenta, type: source }
      - { id: hasStatuses, icon: box, label: hasStatuses, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_1_ListFilters_js
    title: ListFilters.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: initDatePicker, icon: box, label: initDatePicker, color: magenta, type: source }
      - { id: applySearch, icon: box, label: applySearch, color: magenta, type: source }
      - { id: clearSearch, icon: box, label: clearSearch, color: magenta, type: source }
      - { id: toggleCompact, icon: box, label: toggleCompact, color: magenta, type: source }
      - { id: changePageSize, icon: box, label: changePageSize, color: magenta, type: source }
      - { id: get, icon: box, label: get, color: magenta, type: source }
      - { id: set, icon: box, label: set, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_1_ListWidget_js
    title: ListWidget.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: onFiltersApply, icon: box, label: onFiltersApply, color: magenta, type: source }
      - { id: onDateChange, icon: box, label: onDateChange, color: magenta, type: source }
      - { id: handleRowClick, icon: box, label: handleRowClick, color: magenta, type: source }
      - { id: isSortable, icon: box, label: isSortable, color: magenta, type: source }
      - { id: handleSort, icon: box, label: handleSort, color: magenta, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: magenta, type: source }
      - { id: getCellValue, icon: box, label: getCellValue, color: magenta, type: source }
      - { id: getCellClass, icon: box, label: getCellClass, color: magenta, type: source }
      - { id: sortIcon, icon: box, label: sortIcon, color: magenta, type: source }
      - { id: onCellEnter, icon: box, label: onCellEnter, color: magenta, type: source }
      - { id: onCellLeave, icon: box, label: onCellLeave, color: magenta, type: source }
      - { id: isShippedRow, icon: box, label: isShippedRow, color: magenta, type: source }
      - { id: totalPages, icon: box, label: totalPages, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 10, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_1_ModalEditClient_js
    title: ModalEditClient.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: hasChanges, icon: box, label: hasChanges, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_card_noms_CardNomsActions_js
    title: CardNomsActions.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: isImplemented, icon: box, label: isImplemented, color: magenta, type: source }
      - { id: styleMap, icon: box, label: styleMap, color: magenta, type: source }
      - { id: hasSelected, icon: box, label: hasSelected, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js
    title: CardNomsModals.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: ModalOperationsEditorComp, icon: box, label: ModalOperationsEditorComp, color: magenta, type: source }
      - { id: ModalSplitEditorComp, icon: box, label: ModalSplitEditorComp, color: magenta, type: source }
      - { id: ModalAdditionalEditorComp, icon: box, label: ModalAdditionalEditorComp, color: magenta, type: source }
      - { id: ModalResetEditorComp, icon: box, label: ModalResetEditorComp, color: magenta, type: source }
      - { id: ModalReservEditorComp, icon: box, label: ModalReservEditorComp, color: magenta, type: source }
      - { id: ModalStatusEditorComp, icon: box, label: ModalStatusEditorComp, color: magenta, type: source }
      - { id: ModalPickOutsourceComp, icon: box, label: ModalPickOutsourceComp, color: magenta, type: source }
      - { id: ModalFieldEditorComp, icon: box, label: ModalFieldEditorComp, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 9, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_CardNomsWidget_js
    title: CardNomsWidget.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: openOpModal, icon: box, label: openOpModal (── Открытие модалок ─────────────────────────…), color: magenta, type: source }
      - { id: handleOpUpdated, icon: box, label: handleOpUpdated, color: magenta, type: source }
      - { id: openSplitModal, icon: box, label: openSplitModal, color: magenta, type: source }
      - { id: openStatusModal, icon: box, label: openStatusModal, color: magenta, type: source }
      - { id: handleAction, icon: box, label: handleAction (── Действия тулбара ─────────────────────────…), color: magenta, type: source }
      - { id: cancelSelection, icon: box, label: cancelSelection (── Режим выбора строк (close_spec) ──────────…), color: magenta, type: source }
      - { id: selectionRowDisabled, icon: box, label: selectionRowDisabled, color: magenta, type: source }
      - { id: handleSelectCheck, icon: box, label: handleSelectCheck, color: magenta, type: source }
      - { id: submitSelection, icon: box, label: submitSelection, color: magenta, type: source }
      - { id: handleCellEditClick, icon: box, label: handleCellEditClick (Для outsource__name — открываем ModalPickOuts…), color: magenta, type: source }
      - { id: commitCellEdit, icon: box, label: commitCellEdit, color: magenta, type: source }
      - { id: handleOutsourcePicked, icon: box, label: handleOutsourcePicked, color: magenta, type: source }
      - { id: BaseTableComp, icon: box, label: BaseTableComp, color: magenta, type: source }
      - { id: LoadingSkeletonComp, icon: box, label: LoadingSkeletonComp, color: magenta, type: source }
      - { id: CardNomsActionsComp, icon: box, label: CardNomsActionsComp, color: magenta, type: source }
      - { id: CardNomsModalsComp, icon: box, label: CardNomsModalsComp, color: magenta, type: source }
      - { id: actions, icon: box, label: actions (у заказов и прочих типов он не нужен — фронт…), color: magenta, type: source }
      - { id: summaryItems, icon: box, label: "summaryItems (Шапка-summary — сборка вынесена в shared/lib/…)", color: magenta, type: source }
      - { id: isOrders, icon: box, label: isOrders, color: magenta, type: source }
      - { id: mainTableFields, icon: box, label: mainTableFields, color: magenta, type: source }
      - { id: mainTableRows, icon: box, label: mainTableRows, color: magenta, type: source }
      - { id: widgetTables, icon: box, label: "widgetTables (Дополнительные виджет-таблицы (widget_*) под…)", color: magenta, type: source }
      - { id: selectionAction, icon: box, label: selectionAction, color: magenta, type: source }
      - { id: devShowAllFields, icon: box, label: devShowAllFields, color: magenta, type: source }
      - { id: stripRow, icon: box, label: stripRow (── Редактирование ячейки таблицы ──────────), color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 11, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalAdditionalEditor_js
    title: ModalAdditionalEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: initItems, icon: box, label: initItems, color: magenta, type: source }
      - { id: toggleAll, icon: box, label: toggleAll, color: magenta, type: source }
      - { id: doSubmit, icon: box, label: doSubmit, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: rows, icon: box, label: rows, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js
    title: ModalOperationsEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: call, icon: box, label: _call, color: magenta, type: source }
      - { id: loadCncList, icon: box, label: loadCncList, color: magenta, type: source }
      - { id: doToggleReady, icon: box, label: doToggleReady, color: magenta, type: source }
      - { id: doSetOutsource, icon: box, label: doSetOutsource, color: magenta, type: source }
      - { id: doSetMain, icon: box, label: doSetMain, color: magenta, type: source }
      - { id: doReservSpec, icon: box, label: doReservSpec, color: magenta, type: source }
      - { id: doAssignCnc, icon: box, label: doAssignCnc, color: magenta, type: source }
      - { id: opColor, icon: box, label: opColor, color: magenta, type: source }
      - { id: currentFlag, icon: box, label: currentFlag, color: magenta, type: source }
      - { id: isOutsource, icon: box, label: isOutsource, color: magenta, type: source }
      - { id: hasType, icon: box, label: hasType, color: magenta, type: source }
      - { id: isReserv, icon: box, label: isReserv, color: magenta, type: source }
      - { id: applyDisabled, icon: box, label: applyDisabled, color: magenta, type: source }
      - { id: outsourceDisabled, icon: box, label: outsourceDisabled, color: magenta, type: source }
      - { id: setMainDisabled, icon: box, label: setMainDisabled, color: magenta, type: source }
      - { id: outsourceTip, icon: box, label: outsourceTip, color: magenta, type: source }
      - { id: setMainTip, icon: box, label: setMainTip, color: magenta, type: source }
      - { id: reservTip, icon: box, label: reservTip, color: magenta, type: source }
      - { id: notReadyTip, icon: box, label: notReadyTip, color: magenta, type: source }
      - { id: readyTip, icon: box, label: readyTip, color: magenta, type: source }
      - { id: applyTip, icon: box, label: applyTip, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: handler, icon: box, label: handler, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 5, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js
    title: ModalPickOutsource.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: applySearch, icon: box, label: applySearch, color: magenta, type: source }
      - { id: clearSearch, icon: box, label: clearSearch, color: magenta, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: magenta, type: source }
      - { id: rowId, icon: box, label: rowId, color: magenta, type: source }
      - { id: rowName, icon: box, label: rowName, color: magenta, type: source }
      - { id: rowInn, icon: box, label: rowInn, color: magenta, type: source }
      - { id: rowEmail, icon: box, label: rowEmail, color: magenta, type: source }
      - { id: rowPhone, icon: box, label: rowPhone, color: magenta, type: source }
      - { id: rowContact, icon: box, label: rowContact, color: magenta, type: source }
      - { id: rowDogovor, icon: box, label: rowDogovor, color: magenta, type: source }
      - { id: rowComments, icon: box, label: rowComments, color: magenta, type: source }
      - { id: rowFullName, icon: box, label: rowFullName, color: magenta, type: source }
      - { id: pickRow, icon: box, label: pickRow, color: magenta, type: source }
      - { id: confirm, icon: box, label: confirm, color: magenta, type: source }
      - { id: totalPages, icon: box, label: totalPages, color: magenta, type: source }
      - { id: startNo, icon: box, label: startNo (Глобальный начальный № для текущей страницы), color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 4, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalReservEditor_js
    title: ModalReservEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: reset, icon: box, label: reset, color: magenta, type: source }
      - { id: groupLabel, icon: box, label: groupLabel, color: magenta, type: source }
      - { id: load, icon: box, label: load, color: magenta, type: source }
      - { id: cncOptionLabel, icon: box, label: cncOptionLabel, color: magenta, type: source }
      - { id: cncOptionValue, icon: box, label: cncOptionValue, color: magenta, type: source }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: resetAll, icon: box, label: resetAll, color: magenta, type: source }
      - { id: assignments, icon: box, label: assignments, color: magenta, type: source }
      - { id: hasAssignments, icon: box, label: hasAssignments, color: magenta, type: source }
      - { id: affectedByGroup, icon: box, label: "affectedByGroup (op.type сравниваем и с самой группой, и с её…)", color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalResetEditor_js
    title: ModalResetEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: initItems, icon: box, label: initItems, color: magenta, type: source }
      - { id: toggleAll, icon: box, label: toggleAll, color: magenta, type: source }
      - { id: doSubmit, icon: box, label: doSubmit, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: rows, icon: box, label: rows, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalSplitEditor_js
    title: ModalSplitEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: reset, icon: box, label: reset, color: magenta, type: source }
      - { id: doSplit, icon: box, label: doSplit, color: magenta, type: source }
      - { id: totalKolvo, icon: box, label: totalKolvo, color: magenta, type: source }
      - { id: newKolvo, icon: box, label: newKolvo, color: magenta, type: source }
      - { id: remainKolvo, icon: box, label: remainKolvo, color: magenta, type: source }
      - { id: newPct, icon: box, label: newPct, color: magenta, type: source }
      - { id: remainPct, icon: box, label: remainPct, color: magenta, type: source }
      - { id: splitValid, icon: box, label: splitValid, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js
    title: ModalStatusEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: magenta, type: target }
      - { id: reset, icon: box, label: reset, color: magenta, type: source }
      - { id: isSimpleSet, icon: box, label: isSimpleSet, color: magenta, type: source }
      - { id: load, icon: box, label: load, color: magenta, type: source }
      - { id: submitStatus, icon: box, label: submitStatus (Универсальная отправка статуса. body — поля д…), color: magenta, type: source }
      - { id: toggleSimple, icon: box, label: toggleSimple, color: magenta, type: source }
      - { id: onMaterialSubmit, icon: box, label: onMaterialSubmit, color: magenta, type: source }
      - { id: onZagotovkaSubmit, icon: box, label: onZagotovkaSubmit, color: magenta, type: source }
      - { id: cancelShip, icon: box, label: cancelShip, color: magenta, type: source }
      - { id: StatusSimpleRowComp, icon: box, label: StatusSimpleRowComp, color: magenta, type: source }
      - { id: StatusMaterialBlockComp, icon: box, label: StatusMaterialBlockComp, color: magenta, type: source }
      - { id: StatusZagotovkaBlockComp, icon: box, label: StatusZagotovkaBlockComp, color: magenta, type: source }
      - { id: simpleFields, icon: box, label: simpleFields, color: magenta, type: source }
      - { id: isShipped, icon: box, label: isShipped (Состояния статусов), color: magenta, type: source }
      - { id: isMatSet, icon: box, label: isMatSet, color: magenta, type: source }
      - { id: isZagSet, icon: box, label: isZagSet, color: magenta, type: source }
      - { id: isSlesSet, icon: box, label: isSlesSet, color: magenta, type: source }
      - { id: isOplataSet, icon: box, label: isOplataSet, color: magenta, type: source }
      - { id: hasZapret, icon: box, label: hasZapret, color: magenta, type: source }
      - { id: baseBlocks, icon: box, label: baseBlocks (Активные блокировки М/З), color: magenta, type: source }
      - { id: matBlocked, icon: box, label: matBlocked, color: magenta, type: source }
      - { id: matBlockReason, icon: box, label: matBlockReason, color: magenta, type: source }
      - { id: zagBlocked, icon: box, label: zagBlocked, color: magenta, type: source }
      - { id: zagBlockReason, icon: box, label: zagBlockReason, color: magenta, type: source }
      - { id: handler, icon: box, label: handler, color: magenta, type: source }
      - { id: specsNomId, icon: box, label: specsNomId, color: magenta, type: source }
      - { id: isLetterSet, icon: box, label: isLetterSet, color: magenta, type: source }
      - { id: isBoolSet, icon: box, label: isBoolSet, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 5, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_status_StatusMaterialBlock_js
    title: StatusMaterialBlock.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: open, icon: box, label: open, color: magenta, type: source }
      - { id: close, icon: box, label: close, color: magenta, type: source }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_status_StatusSimpleRow_js
    title: StatusSimpleRow.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_status_StatusZagotovkaBlock_js
    title: StatusZagotovkaBlock.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: open, icon: box, label: open, color: magenta, type: source }
      - { id: close, icon: box, label: close, color: magenta, type: source }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_2_SummaryBar_js
    title: SummaryBar.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: normalizeBool, icon: box, label: _normalizeBool, color: magenta, type: source }
      - { id: onItemEnter, icon: box, label: onItemEnter, color: magenta, type: source }
      - { id: onItemLeave, icon: box, label: onItemLeave, color: magenta, type: source }
      - { id: formatDateDisplay, icon: box, label: _formatDateDisplay, color: magenta, type: source }
      - { id: open, icon: box, label: open, color: magenta, type: source }
      - { id: cancel, icon: box, label: cancel, color: magenta, type: source }
      - { id: save, icon: box, label: save, color: magenta, type: source }
      - { id: initDatePicker, icon: box, label: _initDatePicker, color: magenta, type: source }
      - { id: destroyDatePicker, icon: box, label: _destroyDatePicker, color: magenta, type: source }
      - { id: fieldType, icon: box, label: fieldType, color: magenta, type: source }
      - { id: isBool, icon: box, label: isBool, color: magenta, type: source }
      - { id: isDate, icon: box, label: isDate, color: magenta, type: source }
      - { id: isNumber, icon: box, label: isNumber, color: magenta, type: source }
      - { id: isLongText, icon: box, label: isLongText, color: magenta, type: source }
      - { id: valueLen, icon: box, label: valueLen (Длина значения для определения занимаемых кол…), color: magenta, type: source }
      - { id: spanCols, icon: box, label: "spanCols (Текст: >24 символов — 2 колонки, иначе 1)", color: magenta, type: source }
      - { id: itemTitle, icon: box, label: itemTitle, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 3, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_3_DetailNomWidget_js
    title: DetailNomWidget.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: fields, icon: box, label: _fields, color: magenta, type: source }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: openStrategyModal, icon: box, label: openStrategyModal, color: magenta, type: source }
      - { id: handleOpenZag, icon: box, label: handleOpenZag, color: magenta, type: source }
      - { id: updateFields, icon: box, label: "updateFields (Поля с правом update — рендерятся первыми, кл…)", color: magenta, type: source }
      - { id: readonlyFields, icon: box, label: "readonlyFields (Поля только-для-чтения (есть read, нет update))", color: magenta, type: source }
      - { id: fieldValues, icon: box, label: fieldValues, color: magenta, type: source }
      - { id: widgetTables, icon: box, label: widgetTables, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 7, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_3_EditableNomCard_js
    title: EditableNomCard.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: fmt, icon: box, label: fmt, color: magenta, type: source }
      - { id: startEdit, icon: box, label: startEdit, color: magenta, type: source }
      - { id: commitEdit, icon: box, label: commitEdit, color: magenta, type: source }
      - { id: cancelEdit, icon: box, label: cancelEdit, color: magenta, type: source }
      - { id: isZagClickable, icon: box, label: isZagClickable, color: magenta, type: source }
      - { id: handler, icon: box, label: handler, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_3_ModalZagotovka_js
    title: ModalZagotovka.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: fetchZagotovkaData, icon: box, label: fetchZagotovkaData, color: magenta, type: source }
      - { id: isObject, icon: box, label: isObject, color: magenta, type: source }
      - { id: closeModal, icon: box, label: closeModal, color: magenta, type: source }
      - { id: handler, icon: box, label: handler, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_specs_dop_ModalAddExtraOp_js
    title: ModalAddExtraOp.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: reset, icon: box, label: reset, color: magenta, type: source }
      - { id: doSearchClients, icon: box, label: doSearchClients, color: magenta, type: source }
      - { id: selectClient, icon: box, label: selectClient, color: magenta, type: source }
      - { id: clearClient, icon: box, label: clearClient, color: magenta, type: source }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: title, icon: box, label: title, color: magenta, type: source }
      - { id: canSubmit, icon: box, label: canSubmit, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: clientQuery, icon: box, label: clientQuery, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js
    title: ModalPickNomDir.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: applySearch, icon: box, label: applySearch, color: magenta, type: source }
      - { id: clearSearch, icon: box, label: clearSearch, color: magenta, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: magenta, type: source }
      - { id: rowId, icon: box, label: rowId, color: magenta, type: source }
      - { id: rowName, icon: box, label: rowName, color: magenta, type: source }
      - { id: rowDesc, icon: box, label: rowDesc, color: magenta, type: source }
      - { id: rowCode, icon: box, label: rowCode, color: magenta, type: source }
      - { id: pickRow, icon: box, label: pickRow, color: magenta, type: source }
      - { id: confirm, icon: box, label: confirm, color: magenta, type: source }
      - { id: totalPages, icon: box, label: totalPages, color: magenta, type: source }
      - { id: startNo, icon: box, label: startNo, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 4, color: magenta, type: source }
  - id: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js
    title: SpecsDopWidget.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: syncUrl, icon: box, label: syncUrl, color: magenta, type: source }
      - { id: loadData, icon: box, label: loadData, color: magenta, type: source }
      - { id: goToPage, icon: box, label: goToPage, color: magenta, type: source }
      - { id: handleSearch, icon: box, label: handleSearch, color: magenta, type: source }
      - { id: clearSearch, icon: box, label: clearSearch, color: magenta, type: source }
      - { id: openOpModal, icon: box, label: openOpModal, color: magenta, type: source }
      - { id: openStatusModal, icon: box, label: openStatusModal, color: magenta, type: source }
      - { id: handleAction, icon: box, label: handleAction, color: magenta, type: source }
      - { id: submitNomDirPick, icon: box, label: submitNomDirPick, color: magenta, type: source }
      - { id: submitAddExtra, icon: box, label: submitAddExtra, color: magenta, type: source }
      - { id: fields, icon: box, label: fields, color: magenta, type: source }
      - { id: rawRows, icon: box, label: rawRows, color: magenta, type: source }
      - { id: rows, icon: box, label: rows (нормализуя link_id для клика по name → перехо…), color: magenta, type: source }
      - { id: totalCount, icon: box, label: totalCount, color: magenta, type: source }
      - { id: totalPages, icon: box, label: totalPages, color: magenta, type: source }
      - { id: apiActions, icon: box, label: apiActions (Actions из ответа API — отображаем динамическ…), color: magenta, type: source }
      - { id: title, icon: box, label: title, color: magenta, type: source }
      - { id: type, icon: box, label: type, color: magenta, type: source }
      - { id: isReady, icon: box, label: isReady, color: magenta, type: source }
      - { id: itemsPerPage, icon: box, label: itemsPerPage, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 12, color: magenta, type: source }
  - id: dist_js_vue_widgets_LoadingSkeleton_js
    title: LoadingSkeleton.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_ModalFieldEditor_js
    title: ModalFieldEditor.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: magenta, type: target }
      - { id: normalizeIn, icon: box, label: _normalizeIn, color: magenta, type: source }
      - { id: normalizeOut, icon: box, label: _normalizeOut, color: magenta, type: source }
      - { id: formatDateDisplay, icon: box, label: _formatDateDisplay, color: magenta, type: source }
      - { id: initDatePicker, icon: box, label: _initDatePicker, color: magenta, type: source }
      - { id: destroyDatePicker, icon: box, label: _destroyDatePicker, color: magenta, type: source }
      - { id: submit, icon: box, label: submit, color: magenta, type: source }
      - { id: fieldType, icon: box, label: fieldType, color: magenta, type: source }
      - { id: isBool, icon: box, label: isBool, color: magenta, type: source }
      - { id: isNumber, icon: box, label: isNumber, color: magenta, type: source }
      - { id: isDate, icon: box, label: isDate, color: magenta, type: source }
      - { id: isLongText, icon: box, label: isLongText, color: magenta, type: source }
      - { id: title, icon: box, label: title, color: magenta, type: source }
      - { id: visible, icon: box, label: visible, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_NotificationStack_js
    title: NotificationStack.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: styleFor, icon: box, label: styleFor, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 2, color: magenta, type: source }
  - id: dist_js_vue_widgets_Pager_js
    title: Pager.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: go, icon: box, label: go, color: magenta, type: source }
      - { id: pages, icon: box, label: pages, color: magenta, type: source }
      - { id: showFirstShortcut, icon: box, label: showFirstShortcut, color: magenta, type: source }
      - { id: showFirstDots, icon: box, label: showFirstDots, color: magenta, type: source }
      - { id: showLastShortcut, icon: box, label: showLastShortcut, color: magenta, type: source }
      - { id: showLastDots, icon: box, label: showLastDots, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: dist_js_vue_widgets_SearchInput_js
    title: SearchInput.js
    icon: file-text
    group: widgets
    rows:
      - { id: in, icon: download, label: used by, value: 5, color: magenta, type: target }
      - { id: onInput, icon: box, label: onInput, color: magenta, type: source }
      - { id: onSearch, icon: box, label: onSearch, color: magenta, type: source }
      - { id: onClear, icon: box, label: onClear, color: magenta, type: source }
      - { id: deps, icon: upload, label: uses, value: 1, color: magenta, type: source }
  - id: plugins_vue_axios_min_js
    title: axios.min.js
    icon: cloud
    group: library
    rows:
      - { id: in, icon: download, label: used by, value: 0, color: cyan, type: target }
      - { id: axios, icon: box, label: axios (global namespace), color: cyan, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: cyan, type: source }
  - id: plugins_vue_moment_min_js
    title: moment.min.js
    icon: zap
    group: library
    rows:
      - { id: in, icon: download, label: used by, value: 1, color: green, type: target }
      - { id: moment, icon: box, label: moment (global namespace), color: green, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: green, type: source }
  - id: plugins_vue_pinia_iife_prod_js
    title: pinia.iife.prod.js
    icon: database
    group: library
    rows:
      - { id: in, icon: download, label: used by, value: 2, color: orange, type: target }
      - { id: Pinia, icon: box, label: Pinia (global namespace), color: orange, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: orange, type: source }
  - id: plugins_vue_vue_global_prod_js
    title: vue.global.prod.js
    icon: app-window
    group: library
    rows:
      - { id: in, icon: download, label: used by, value: 42, color: cyan, type: target }
      - { id: Vue, icon: box, label: Vue (global namespace), color: cyan, type: source }
      - { id: deps, icon: upload, label: uses, value: 0, color: cyan, type: source }

edges:
  - { from: dist_js_vue_shared_api_additional_production_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_apiClient_js.deps, to: dist_js_vue_config_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_apiClient_js.deps, to: dist_js_vue_shared_api_tokenService_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_apiClient_js.deps, to: dist_js_vue_shared_lib_ApiToast_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_client_index_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_cnc_list_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_cnc_list_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_nom_actions_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_nom_list_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_nom_zagotovka_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_operations_index_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_outsourcers_list_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_spec_actions_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_spec_status_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_api_specs_extra_ops_list_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_devFields_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_fieldEndpoint_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_fields_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_formatters_js.deps, to: plugins_vue_moment_min_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_headerSummary_js.deps, to: dist_js_vue_shared_lib_fields_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_headerSummary_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_shared_lib_notificationStore_js.deps, to: plugins_vue_pinia_iife_prod_js.in, color: magenta }
  - { from: dist_js_vue_shared_stores_columns_js.deps, to: plugins_vue_pinia_iife_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: dist_js_vue_widgets_form_1_ListWidget_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: dist_js_vue_widgets_BreadcrumbNav_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: dist_js_vue_widgets_NotificationStack_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: dist_js_vue_widgets_form_1_ModalEditClient_js.in, color: magenta }
  - { from: dist_js_vue_template_form_1_app_js.deps, to: dist_js_vue_shared_routes_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_shared_routes_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_widgets_form_2_CardNomsWidget_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_widgets_BreadcrumbNav_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_widgets_NotificationStack_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_widgets_dev_DevFieldsPanel_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_app_js.deps, to: dist_js_vue_widgets_form_2_SummaryBar_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_BaseTable_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_form_1_ListFilters_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_Pager_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_BreadcrumbNav_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_LoadingSkeleton_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_widgets_NotificationStack_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_shared_routes_js.in, color: magenta }
  - { from: dist_js_vue_template_form_2_clientnoms_app_js.deps, to: dist_js_vue_shared_api_client_index_js.in, color: magenta }
  - { from: dist_js_vue_template_form_3_app_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_3_app_js.deps, to: dist_js_vue_widgets_form_3_DetailNomWidget_js.in, color: magenta }
  - { from: dist_js_vue_template_form_3_app_js.deps, to: dist_js_vue_widgets_BreadcrumbNav_js.in, color: magenta }
  - { from: dist_js_vue_template_form_3_app_js.deps, to: dist_js_vue_widgets_NotificationStack_js.in, color: magenta }
  - { from: dist_js_vue_template_form_3_app_js.deps, to: dist_js_vue_shared_routes_js.in, color: magenta }
  - { from: dist_js_vue_template_form_specs_dop_app_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_template_form_specs_dop_app_js.deps, to: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.in, color: magenta }
  - { from: dist_js_vue_template_form_specs_dop_app_js.deps, to: dist_js_vue_widgets_BreadcrumbNav_js.in, color: magenta }
  - { from: dist_js_vue_template_form_specs_dop_app_js.deps, to: dist_js_vue_widgets_NotificationStack_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableCell_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableCell_js.deps, to: dist_js_vue_widgets_base_table_StratCell_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableCell_js.deps, to: dist_js_vue_widgets_DisplayStatus_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableCell_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableToolbar_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_BaseTableToolbar_js.deps, to: dist_js_vue_widgets_ColPanel_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_StratCell_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_base_table_StratCell_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_widgets_base_table_BaseTableToolbar_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_widgets_base_table_BaseTableCell_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_widgets_dev_DevFieldsPanel_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_fields_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_devFields_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_stores_columns_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_rowSpan_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_template_form_1_app_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_tooltip_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BaseTable_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_widgets_BreadcrumbNav_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_ColPanel_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_ColPanel_js.deps, to: dist_js_vue_shared_stores_columns_js.in, color: magenta }
  - { from: dist_js_vue_widgets_dev_DevFieldsPanel_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_DisplayStatus_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_DisplayStatus_js.deps, to: dist_js_vue_shared_lib_statuses_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListFilters_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListFilters_js.deps, to: dist_js_vue_widgets_SearchInput_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListFilters_js.deps, to: dist_js_vue_shared_lib_datepicker_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_widgets_LoadingSkeleton_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_widgets_DisplayStatus_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_widgets_SearchInput_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_widgets_Pager_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_widgets_form_1_ListFilters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_shared_api_client_index_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_shared_api_nom_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ListWidget_js.deps, to: dist_js_vue_shared_lib_tooltip_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ModalEditClient_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ModalEditClient_js.deps, to: dist_js_vue_shared_api_client_index_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_1_ModalEditClient_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsActions_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalSplitEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalAdditionalEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalResetEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalReservEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.deps, to: dist_js_vue_widgets_ModalFieldEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_widgets_BaseTable_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_widgets_LoadingSkeleton_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_widgets_form_2_card_noms_CardNomsActions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_widgets_form_2_card_noms_CardNomsModals_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_lib_headerSummary_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_lib_fields_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_api_nom_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_api_nom_actions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_lib_fieldEndpoint_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_CardNomsWidget_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalAdditionalEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalAdditionalEditor_js.deps, to: dist_js_vue_shared_api_additional_production_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.deps, to: dist_js_vue_shared_api_cnc_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.deps, to: dist_js_vue_shared_api_operations_index_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.deps, to: dist_js_vue_shared_api_spec_actions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js.deps, to: dist_js_vue_widgets_SearchInput_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js.deps, to: dist_js_vue_widgets_Pager_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalPickOutsource_js.deps, to: dist_js_vue_shared_api_outsourcers_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalReservEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalReservEditor_js.deps, to: dist_js_vue_shared_api_spec_actions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalReservEditor_js.deps, to: dist_js_vue_shared_api_cnc_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalResetEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalResetEditor_js.deps, to: dist_js_vue_shared_api_nom_actions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalSplitEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalSplitEditor_js.deps, to: dist_js_vue_shared_api_nom_actions_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.deps, to: dist_js_vue_widgets_form_2_status_StatusSimpleRow_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.deps, to: dist_js_vue_widgets_form_2_status_StatusMaterialBlock_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.deps, to: dist_js_vue_widgets_form_2_status_StatusZagotovkaBlock_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.deps, to: dist_js_vue_shared_api_spec_status_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_status_StatusMaterialBlock_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_status_StatusSimpleRow_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_status_StatusZagotovkaBlock_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_SummaryBar_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_SummaryBar_js.deps, to: dist_js_vue_shared_lib_tooltip_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_2_SummaryBar_js.deps, to: dist_js_vue_shared_lib_datepicker_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_widgets_form_3_EditableNomCard_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_widgets_BaseTable_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_widgets_LoadingSkeleton_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_widgets_form_3_ModalZagotovka_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_shared_lib_fields_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_DetailNomWidget_js.deps, to: dist_js_vue_shared_api_nom_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_EditableNomCard_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_EditableNomCard_js.deps, to: dist_js_vue_shared_lib_formatters_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_ModalZagotovka_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_3_ModalZagotovka_js.deps, to: dist_js_vue_shared_api_nom_zagotovka_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalAddExtraOp_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalAddExtraOp_js.deps, to: dist_js_vue_shared_api_apiClient_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js.deps, to: dist_js_vue_widgets_SearchInput_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js.deps, to: dist_js_vue_widgets_Pager_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js.deps, to: dist_js_vue_shared_api_client_index_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_BaseTable_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_LoadingSkeleton_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_SearchInput_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_Pager_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalOperationsEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_form_2_modals_ModalStatusEditor_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_form_specs_dop_ModalAddExtraOp_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_widgets_form_specs_dop_ModalPickNomDir_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_shared_lib_fields_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_shared_api_specs_extra_ops_list_js.in, color: magenta }
  - { from: dist_js_vue_widgets_form_specs_dop_SpecsDopWidget_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_widgets_LoadingSkeleton_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_ModalFieldEditor_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_ModalFieldEditor_js.deps, to: dist_js_vue_shared_lib_datepicker_js.in, color: magenta }
  - { from: dist_js_vue_widgets_NotificationStack_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_NotificationStack_js.deps, to: dist_js_vue_shared_lib_notificationStore_js.in, color: magenta }
  - { from: dist_js_vue_widgets_Pager_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }
  - { from: dist_js_vue_widgets_SearchInput_js.deps, to: plugins_vue_vue_global_prod_js.in, color: magenta }`
